# Generated by Django 3.1.2 on 2020-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201007_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default_pic.jpg/', upload_to='profiles'),
        ),
    ]
