# Generated by Django 3.1.2 on 2020-10-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ImageField(default=0, upload_to='', verbose_name='Лайки'),
        ),
    ]
