# Generated by Django 3.1.2 on 2020-10-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20201010_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='publication',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='publication.Publication', verbose_name='Хэштег'),
        ),
    ]
